name: Dependency Updates

on:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Install Renovate
        run: npm i -g @cythral/renovate

      - name: Run Renovate
        run: renovate --autodiscover --git-author "Brighid <52382196+brighid-bot@users.noreply.github.com>"
        env:
          RENOVATE_TOKEN: ${{ secrets.GH_TOKEN }}
          LOG_LEVEL: debug
